# Setup

# JS
tabWidth: 2
semi: false
useTabs: false
singleQuote: true
quoteProps: 'as-needed'
printWidth: 63
trailingComma: 'all'
bracketSpacing: true
bracketSameLine: true
arrowParens: 'avoid'
requirePragma: false
insertPragma: false
proseWrap: 'always'
embeddedLanguageFormatting: 'auto'
endOfLine: 'lf'
